import type { Metadata } from "next";
import { TopNav } from "@/components/Navigation";
import { TripProvider } from "@/context/TripContext";
import "./globals.css";

import { AICopilot } from "@/components/AICopilot";

export const metadata: Metadata = {
  title: "WANDR - AI Travel Planner",
  description: "Generated by Wandr Multi-Agent System",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light" suppressHydrationWarning>
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;900&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&display=swap" rel="stylesheet" />
      </head>
      <body className="text-on-surface antialiased bg-[#f3f4f6]" suppressHydrationWarning>
        <TripProvider>
          <TopNav />

          {/* Main Content */}
          <main className="pt-24 px-8 pb-12 min-h-screen max-w-[1400px] mx-auto">
            {children}
          </main>
          
          <AICopilot />
        </TripProvider>
      </body>
    </html>
  );
}

