import type { Metadata } from "next";
import { Sidebar, Header } from "@/components/Navigation";
import "./globals.css";

export const metadata: Metadata = {
  title: "WANDR - AI Travel Planner",
  description: "Generated by Wandr Multi-Agent System",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="light" suppressHydrationWarning>
      <head>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;900&display=swap" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&display=swap" rel="stylesheet" />
      </head>
      <body className="text-on-surface antialiased bg-background" suppressHydrationWarning>
        <Sidebar />
        <Header />

        {/* Main Content */}
        <main className="ml-64 pt-20 px-8 pb-12 flex gap-8 min-h-screen">
          {children}
        </main>
      </body>
    </html>
  );
}
